classdef AllTests < matlab.unittest.TestCase
%ALLTESTS Wrapper test class for all modBuilder test scripts.
%
%   Parametrized test class that runs each existing test script through
%   MATLAB's unit testing framework. This allows code coverage collection
%   via CodeCoveragePlugin while reusing existing test scripts as-is.

    properties (TestParameter)
        testname = AllTests.buildTestParams();
    end

    methods (Test)
        function runTestScript(testCase, testname) %#ok<INUSL>
            runtest(testname);
        end
    end

    methods (Static, Access = private)
        function params = buildTestParams()
            % Read the test list generated by Meson at configure time.
            testlistfile = fullfile(fileparts(mfilename('fullpath')), 'testlist.txt');
            assert(isfile(testlistfile), ...
                   'AllTests:missingTestList', ...
                   ['testlist.txt not found. Run ''meson setup'' first ' ...
                    '(see README.md § Test Suite).']);
            names = readlines(testlistfile);
            names = names(strlength(names) > 0);
            names = cellstr(names);
            params = struct();
            for i = 1:numel(names)
                key = regexprep(names{i}, '\.m$', '');
                key = strrep(key, '/', '_');
                key = strrep(key, '-', '_');
                params.(key) = names{i};
            end
        end
    end

end
