function names = statement_keywords()
% The keywords that open a Dynare statement at the top level of a .mod file.
%
% OUTPUTS:
% - names   [cell]   1×n array of char arrays
%
% REMARKS:
% - Extracted from the <INITIAL> rules of Dynare's preprocessor/src/DynareFlex.ll: a
%   line whose first token is neither one of these nor a declared symbol is a native
%   MATLAB statement for Dynare, which passes it through to the end of the line. The
%   reader skips such a line, see modfile.split_statements.
    names = {'bvar_density', 'bvar_forecast', 'bvar_irf', 'calib_smoother', 'change_type', ...
             'check', 'compilation_setup', 'conditional_forecast', 'conditional_forecast_paths', ...
             'corr', 'data', 'database', 'deterministic_trends', 'discretionary_policy', ...
             'dsample', 'dynasave', 'dynatype', 'endval', 'epilogue', 'estimated_params', ...
             'estimated_params_bounds', 'estimated_params_init', 'estimated_params_remove', ...
             'estimation', 'evaluate_planner_objective', 'extended_path', 'external_function', ...
             'filter_initial_state', 'filter_tunes', 'forecast', 'generate_irfs', ...
             'heterogeneity_compute_steady_state', 'heterogeneity_dimension', ...
             'heterogeneity_load_steady_state', 'heterogeneity_simulate', 'heterogeneity_solve', ...
             'heteroskedastic_shocks', 'histval', 'histval_file', 'homotopy_setup', ...
             'identification', 'init2shocks', 'initial_condition_decomposition', 'initval', ...
             'initval_file', 'irf_calibration', 'load_params_and_steady_state', 'log_trend_var', ...
             'markov_switching', 'matched_irfs', 'matched_irfs_weights', 'matched_moments', ...
             'method_of_moments', 'model', 'model_comparison', 'model_diagnostics', 'model_info', ...
             'model_local_variable', 'model_options', 'model_remove', 'model_replace', ...
             'moment_calibration', 'ms_compute_mdd', 'ms_compute_probabilities', 'ms_estimation', ...
             'ms_forecast', 'mshocks', 'ms_irf', 'ms_simulation', 'ms_variance_decomposition', ...
             'observation_trends', 'occbin_constraints', 'occbin_graph', 'occbin_setup', ...
             'occbin_solver', 'occbin_write_regimes', 'optim_weights', 'osr', 'osr_params', ...
             'osr_params_bounds', 'pac_model', 'pac_target_info', 'parameters', ...
             'perfect_foresight_controlled_paths', 'perfect_foresight_setup', ...
             'perfect_foresight_solver', 'perfect_foresight_with_expectation_errors_setup', ...
             'perfect_foresight_with_expectation_errors_solver', 'planner_objective', ...
             'plot_conditional_forecast', 'plot_shock_decomposition', 'posterior_function', ...
             'predetermined_variables', 'prior_function', 'priors', 'ramsey_constraints', ...
             'ramsey_model', 'ramsey_policy', 'realtime_shock_decomposition', 'resid', 'rplot', ...
             'save_params_and_steady_state', 'sbvar', 'sensitivity', 'set_time', ...
             'shock_decomposition', 'shock_groups', 'shock_paths', 'shocks', 'simul', ...
             'smoother2histval', 'squeeze_shock_decomposition', 'std', 'steady', ...
             'steady_state_model', 'stoch_simul', 'svar', 'svar_global_identification_check', ...
             'svar_identification', 'trend_component_model', 'trend_var', 'var', 'varexo', ...
             'varexo_det', 'var_expectation_model', 'var_model', 'varobs', 'var_remove', ...
             'verbatim', 'write_latex_dynamic_model', 'write_latex_original_model', ...
             'write_latex_static_model', 'write_latex_steady_state_model'};
end
